version: "3.1"

services:
#  db:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: app
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - 3306:3306
#
#  rabbitmq:
#    container_name: rabbitmq
#    image: "rabbitmq:3-management"
#    hostname: "rabbitmq"
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBITMQ_DEFAULT_USER: "user"
#      RABBITMQ_DEFAULT_PASS: "pass"
#      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    restart: always
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      ENV_NAME: dev
#    ports:
#      - 7001:7001

volumes:
  db_data: { }