version: "3.1"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3307
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      ENV_NAME: dev
#    ports:
#      - 7001:7001
volumes:
  db_data: { }